import enum


class UserStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    DELETED = "DELETED"


class ProviderStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"


class DeviceStatus(str, enum.Enum):
    ENROLLING = "ENROLLING"
    BENCHMARKING = "BENCHMARKING"
    ACTIVE = "ACTIVE"
    IDLE = "IDLE"
    RUNNING = "RUNNING"
    THROTTLED = "THROTTLED"
    COOLING = "COOLING"
    OFFLINE = "OFFLINE"
    QUARANTINED = "QUARANTINED"
    SUSPENDED = "SUSPENDED"
    RETIRED = "RETIRED"


class RoleName(str, enum.Enum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    FINANCE = "FINANCE"
    OPERATIONS = "OPERATIONS"
    DEVELOPER = "DEVELOPER"
    CUSTOMER = "CUSTOMER"
    PROVIDER = "PROVIDER"
    SUPPORT = "SUPPORT"
    NODE = "NODE"


class WalletChainFamily(str, enum.Enum):
    EVM = "evm"
    SOLANA = "solana"
    BITCOIN = "bitcoin"


class WalletVerificationStatus(str, enum.Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


class JobStatus(str, enum.Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    QUEUED = "QUEUED"
    MATCHED = "MATCHED"
    DISPATCHED = "DISPATCHED"
    ACCEPTED = "ACCEPTED"
    RUNNING = "RUNNING"
    RESULT_SUBMITTED = "RESULT_SUBMITTED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    REVENUE_PENDING = "REVENUE_PENDING"
    REVENUE_CONFIRMED = "REVENUE_CONFIRMED"
    SETTLED = "SETTLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    INVALID_RESULT = "INVALID_RESULT"
    CANCELLED = "CANCELLED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    QUARANTINED = "QUARANTINED"


class JobEventActorType(str, enum.Enum):
    SYSTEM = "SYSTEM"
    NODE = "NODE"
    USER = "USER"
    ADMIN = "ADMIN"
    CUSTOMER = "CUSTOMER"


class WithdrawalStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    SECURITY_HOLD = "SECURITY_HOLD"
    RISK_REVIEW = "RISK_REVIEW"
    APPROVED = "APPROVED"
    BROADCAST = "BROADCAST"
    CONFIRMING = "CONFIRMING"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class LedgerDirection(str, enum.Enum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class LedgerAccountType(str, enum.Enum):
    PROVIDER_PAYABLE = "PROVIDER_PAYABLE"
    PROVIDER_PENDING = "PROVIDER_PENDING"
    CUSTOMER_PREPAID = "CUSTOMER_PREPAID"
    REVENUE_CLEARING = "REVENUE_CLEARING"
    TREASURY_CASH = "TREASURY_CASH"
    INFRASTRUCTURE_RECOVERY = "INFRASTRUCTURE_RECOVERY"
    FARMOS_REVENUE = "FARMOS_REVENUE"
    OPERATING_RESERVE = "OPERATING_RESERVE"
    HARDWARE_REINVESTMENT = "HARDWARE_REINVESTMENT"


class OpportunityStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    EXPIRED = "EXPIRED"
    UNSCORABLE = "UNSCORABLE"


class AuditEventType(str, enum.Enum):
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    USER_REGISTERED = "USER_REGISTERED"
    WALLET_VERIFIED = "WALLET_VERIFIED"
    WALLET_VERIFICATION_FAILED = "WALLET_VERIFICATION_FAILED"
    DEVICE_ENROLLED = "DEVICE_ENROLLED"
    DEVICE_QUARANTINED = "DEVICE_QUARANTINED"
    DEVICE_RELEASED = "DEVICE_RELEASED"
    DEVICE_RETIRED = "DEVICE_RETIRED"
    JOB_ASSIGNED = "JOB_ASSIGNED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    RESULT_VERIFIED = "RESULT_VERIFIED"
    RESULT_REJECTED = "RESULT_REJECTED"
    LEDGER_POSTED = "LEDGER_POSTED"
    WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED"
    WITHDRAWAL_APPROVED = "WITHDRAWAL_APPROVED"
    WITHDRAWAL_REJECTED = "WITHDRAWAL_REJECTED"
    PAYOUT_BROADCAST = "PAYOUT_BROADCAST"
    PAYOUT_CONFIRMED = "PAYOUT_CONFIRMED"
    ADAPTER_DISABLED = "ADAPTER_DISABLED"
    ADAPTER_ENABLED = "ADAPTER_ENABLED"
    SETTINGS_CHANGED = "SETTINGS_CHANGED"
    PROVIDER_CREATED = "PROVIDER_CREATED"
    PROVIDER_STATUS_CHANGED = "PROVIDER_STATUS_CHANGED"
    FARM_CREATED = "FARM_CREATED"