# Alembic configuration for FARMOS

[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql+asyncpg://farmos:farmos@localhost:5432/farmos

[post_write_hooks]
hooks = black, isort, ruff
black.type = console_scripts
black.entrypoint = black
black.options = -l 100
isort.type = console_scripts
isort.entrypoint = isort
isort.options = --profile black -l 100
ruff.type = console_scripts
ruff.entrypoint = ruff
ruff.options = format --line-length 100

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
